### PR TITLE
Fix issue when cookies are disabled

### PR DESCRIPTION
**Pull request by mohd-akram**
Chrome raises a SecurityError when localStorage is accessed while cookies are disabled.

### CODE REVIEW

**Comment by blainsmith** [comment]
Could you add supporting tests for this please?

**Comment by mohd-akram** [comment]
It seems Phantom doesn't have a way to [disable localStorage](https://github.com/ariya/phantomjs/issues/11055), so not sure how to write a test for this.

**Comment by blainsmith** [comment]
I see this http://phantomjs.org/api/phantom/property/cookies-enabled.html, however I think the test suite may need some attention to get updated to take advantage of this.

**Comment by mohd-akram** [comment]
I ran the existing tests in Chrome with cookies disabled by [following this](http://derickbailey.com/2014/07/03/debugging-browserified-unit-tests-in-a-real-browser/) (although I had to do `grunt jasmine connect watch`) and all of them failed as they access localStorage directly. I've updated the tests, now they should pass with my fix and fail immediately without it.

**Pull request closed without merging**
